In [59]:
import pandas as pd
import numpy as np

In [22]:
matches = pd.read_csv("C:\\Users\\isabo\\Downloads\\England_22_23.csv", index_col=0)

In [23]:
matches.head()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
Div,,,,,,,,,,,,,,,,,,,,,
E0,05/08/2022,20:00,Crystal Palace,Arsenal,0,2,A,0,1,A,...,1.76,0.50,2.09,1.84,2.04,1.88,2.09,1.88,2.03,1.85
E0,06/08/2022,12:30,Fulham,Liverpool,2,2,D,1,0,H,...,2.73,1.75,1.90,2.03,1.91,2.02,2.01,2.06,1.89,1.99
E0,06/08/2022,15:00,Bournemouth,Aston Villa,2,0,H,1,0,H,...,1.76,0.50,1.93,2.00,1.93,2.00,1.94,2.04,1.88,2.00
E0,06/08/2022,15:00,Leeds,Wolves,2,1,H,1,1,D,...,1.87,-0.25,2.08,1.85,2.10,1.84,2.14,1.87,2.08,1.81
E0,06/08/2022,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,D,...,1.89,-1.00,1.97,1.96,1.99,1.93,2.19,1.97,2.03,1.86

In [24]:
matches.shape

(380, 105)

In [32]:
matches["HomeTeam"].value_counts()

HomeTeam
Crystal Palace    19
Fulham            19
Chelsea           19
Nott'm Forest     19
Brentford         19
Wolves            19
Southampton       19
Man City          19
Brighton          19
Arsenal           19
Aston Villa       19
West Ham          19
Man United        19
Leicester         19
Everton           19
Tottenham         19
Newcastle         19
Leeds             19
Bournemouth       19
Liverpool         19
Name: count, dtype: int64

In [43]:
matches.dtypes

Date         datetime64[ns]
Time                 object
HomeTeam             object
AwayTeam             object
FTHG                  int64
                  ...
MaxCAHH             float64
MaxCAHA             float64
AvgCAHH             float64
AvgCAHA             float64
home_code              int8
Length: 106, dtype: object

In [39]:
matches["Date"] = pd.to_datetime(matches["Date"], format="%d/%m/%Y")

In [46]:
matches["home_code"] = matches["HomeTeam"].astype("category").cat.codes
matches["away_code"] = matches["AwayTeam"].astype("category").cat.codes

In [50]:
matches["hour"] = matches["Time"].str.replace(":.+", "",regex =True).astype("int")

In [51]:
matches

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,home_code,away_code,hour
Div,,,,,,,,,,,,,,,,,,,,,
E0,2022-08-05,20:00,Crystal Palace,Arsenal,0,2,A,0,1,A,...,1.84,2.04,1.88,2.09,1.88,2.03,1.85,6,0,20
E0,2022-08-06,12:30,Fulham,Liverpool,2,2,D,1,0,H,...,2.03,1.91,2.02,2.01,2.06,1.89,1.99,8,11,12
E0,2022-08-06,15:00,Bournemouth,Aston Villa,2,0,H,1,0,H,...,2.00,1.93,2.00,1.94,2.04,1.88,2.00,2,1,15
E0,2022-08-06,15:00,Leeds,Wolves,2,1,H,1,1,D,...,1.85,2.10,1.84,2.14,1.87,2.08,1.81,9,19,15
E0,2022-08-06,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,D,...,1.96,1.99,1.93,2.19,1.97,2.03,1.86,14,15,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E0,2023-05-28,16:30,Everton,Bournemouth,1,0,H,0,0,D,...,1.77,2.10,1.81,2.17,1.92,2.03,1.83,7,2,16
E0,2023-05-28,16:30,Leeds,Tottenham,1,4,A,0,1,A,...,2.06,1.83,2.10,1.90,2.14,1.81,2.06,9,17,16
E0,2023-05-28,16:30,Leicester,West Ham,2,1,H,1,0,H,...,2.05,1.85,2.06,1.90,2.16,1.82,2.04,10,18,16
E0,2023-05-28,16:30,Man United,Fulham,2,1,H,1,1,D,...,1.92,1.98,1.93,2.07,1.98,1.97,1.89,13,8,16
E0,2023-05-28,16:30,Southampton,Liverpool,4,4,D,2,2,D,...,2.08,1.85,2.07,1.96,2.12,1.88,1.98,16,11,16

In [53]:
matches["day_code"] = matches["Date"].dt.dayofweek

In [108]:
matches

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AvgCAHA,home_code,away_code,hour,day_code,target,team,home_win,away_win,win
Div,,,,,,,,,,,,,,,,,,,,,
E0,2022-08-05,20:00,Crystal Palace,Arsenal,0,2,A,0,1,A,...,1.85,6,0,20,4,Draw,-1,0,1,1
E0,2022-08-06,12:30,Fulham,Liverpool,2,2,D,1,0,H,...,1.99,8,11,12,5,Draw,-1,0,0,0
E0,2022-08-06,15:00,Bournemouth,Aston Villa,2,0,H,1,0,H,...,2.00,2,1,15,5,Draw,-1,1,0,1
E0,2022-08-06,15:00,Leeds,Wolves,2,1,H,1,1,D,...,1.81,9,19,15,5,Home Team Wins,-1,1,0,1
E0,2022-08-06,15:00,Newcastle,Nott'm Forest,2,0,H,0,0,D,...,1.86,14,15,15,5,Draw,-1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E0,2023-05-28,16:30,Everton,Bournemouth,1,0,H,0,0,D,...,1.83,7,2,16,6,Home Team Wins,-1,1,0,1
E0,2023-05-28,16:30,Leeds,Tottenham,1,4,A,0,1,A,...,2.06,9,17,16,6,Away Team Wins,-1,0,1,1
E0,2023-05-28,16:30,Leicester,West Ham,2,1,H,1,0,H,...,2.04,10,18,16,6,Draw,-1,1,0,1
E0,2023-05-28,16:30,Man United,Fulham,2,1,H,1,1,D,...,1.89,13,8,16,6,Home Team Wins,-1,1,0,1
E0,2023-05-28,16:30,Southampton,Liverpool,4,4,D,2,2,D,...,1.98,16,11,16,6,Draw,-1,0,0,0

In [107]:
matches["home_win"] = (matches["FTR"] == "H").astype("int")
matches["away_win"] = (matches["FTR"] == "A").astype("int")
unique_teams = pd.concat([matches["home_code"], matches["away_code"]]).unique()

# Initialize the "win" column with 0
matches["win"] = 0

# Update the "win" column based on the desired logic
for team in unique_teams:
    matches.loc[((matches["home_code"] == team) & (matches["home_win"] == 1)) | ((matches["away_code"] == team) & (matches["away_win"] == 1)), "win"] = 1

In [157]:
from sklearn.ensemble import RandomForestClassifier

In [158]:
train = matches[matches["Date"] < '2023-01-01']

In [159]:
test = matches[matches["Date"] > '2023-01-01']

In [160]:
predictors = ["home_code","away_code","hour","day_code","home_win","away_win"]

In [161]:
rf = RandomForestClassifier(n_estimators=50,min_samples_split=10, random_state=1)

In [162]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [163]:
preds = rf.predict(test[predictors])

In [164]:
from sklearn.metrics import accuracy_score

In [165]:
acc = accuracy_score(test["target"], preds)

In [166]:
acc

0.6495327102803738

In [167]:
combined = pd.DataFrame(dict(actual=test["target"],prediction=preds))

In [168]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction      Away Team Wins  Draw  Home Team Wins
actual
Away Team Wins               2    21               0
Draw                         1   108              24
Home Team Wins               0    29              29